export const countries = [
  { code: "SY", name: "سوريا", dialCode: "+963", maxLength: 9 },
  { code: "SA", name: "السعودية", dialCode: "+966", maxLength: 9 },
  { code: "AE", name: "الإمارات", dialCode: "+971", maxLength: 9 },
  { code: "EG", name: "مصر", dialCode: "+20", maxLength: 10 },
  { code: "JO", name: "الأردن", dialCode: "+962", maxLength: 9 },
  { code: "LB", name: "لبنان", dialCode: "+961", maxLength: 8 },
  { code: "IQ", name: "العراق", dialCode: "+964", maxLength: 10 },
  { code: "KW", name: "الكويت", dialCode: "+965", maxLength: 8 },
  { code: "QA", name: "قطر", dialCode: "+974", maxLength: 8 },
  { code: "BH", name: "البحرين", dialCode: "+973", maxLength: 8 },
  { code: "OM", name: "عُمان", dialCode: "+968", maxLength: 8 },
  { code: "YE", name: "اليمن", dialCode: "+967", maxLength: 9 },
  { code: "PS", name: "فلسطين", dialCode: "+970", maxLength: 9 },
  { code: "DZ", name: "الجزائر", dialCode: "+213", maxLength: 9 },
  { code: "MA", name: "المغرب", dialCode: "+212", maxLength: 9 },
  { code: "TN", name: "تونس", dialCode: "+216", maxLength: 8 },
  { code: "LY", name: "ليبيا", dialCode: "+218", maxLength: 9 },
  { code: "SD", name: "السودان", dialCode: "+249", maxLength: 9 },
  { code: "MR", name: "موريتانيا", dialCode: "+222", maxLength: 8 },
  { code: "SO", name: "الصومال", dialCode: "+252", maxLength: 8 },
  { code: "DJ", name: "جيبوتي", dialCode: "+253", maxLength: 8 },
  { code: "KM", name: "جزر القمر", dialCode: "+269", maxLength: 7 },
  { code: "TR", name: "تركيا", dialCode: "+90", maxLength: 10 },
  { code: "US", name: "الولايات المتحدة", dialCode: "+1", maxLength: 10 },
  { code: "GB", name: "بريطانيا", dialCode: "+44", maxLength: 10 },
  { code: "CA", name: "كندا", dialCode: "+1", maxLength: 10 },
  { code: "FR", name: "فرنسا", dialCode: "+33", maxLength: 9 },
  { code: "DE", name: "ألمانيا", dialCode: "+49", maxLength: 11 },
  { code: "RU", name: "روسيا", dialCode: "+7", maxLength: 10 },
  { code: "CN", name: "الصين", dialCode: "+86", maxLength: 11 },
  { code: "IN", name: "الهند", dialCode: "+91", maxLength: 10 },
  { code: "BR", name: "البرازيل", dialCode: "+55", maxLength: 11 },
  { code: "AU", name: "أستراليا", dialCode: "+61", maxLength: 9 },
  { code: "IT", name: "إيطاليا", dialCode: "+39", maxLength: 10 },
  { code: "ES", name: "إسبانيا", dialCode: "+34", maxLength: 9 },
  { code: "NL", name: "هولندا", dialCode: "+31", maxLength: 9 },
  { code: "SE", name: "السويد", dialCode: "+46", maxLength: 9 },
  { code: "CH", name: "سويسرا", dialCode: "+41", maxLength: 9 },
  { code: "AT", name: "النمسا", dialCode: "+43", maxLength: 10 },
  { code: "BE", name: "بلجيكا", dialCode: "+32", maxLength: 9 },
  { code: "DK", name: "الدنمارك", dialCode: "+45", maxLength: 8 },
  { code: "FI", name: "فنلندا", dialCode: "+358", maxLength: 10 },
  { code: "NO", name: "النرويج", dialCode: "+47", maxLength: 8 },
  { code: "IE", name: "أيرلندا", dialCode: "+353", maxLength: 9 },
  { code: "NZ", name: "نيوزيلندا", dialCode: "+64", maxLength: 9 },
  { code: "ZA", name: "جنوب أفريقيا", dialCode: "+27", maxLength: 9 },
  { code: "KR", name: "كوريا الجنوبية", dialCode: "+82", maxLength: 10 },
  { code: "JP", name: "اليابان", dialCode: "+81", maxLength: 10 },
  { code: "SG", name: "سنغافورة", dialCode: "+65", maxLength: 8 },
  { code: "MY", name: "ماليزيا", dialCode: "+60", maxLength: 10 },
  { code: "ID", name: "إندونيسيا", dialCode: "+62", maxLength: 12 },
  { code: "PH", name: "الفلبين", dialCode: "+63", maxLength: 10 },
  { code: "TH", name: "تايلاند", dialCode: "+66", maxLength: 9 },
  { code: "VN", name: "فيتنام", dialCode: "+84", maxLength: 10 },
  { code: "PK", name: "باكستان", dialCode: "+92", maxLength: 10 },
  { code: "BD", name: "بنغلاديش", dialCode: "+880", maxLength: 10 },
  { code: "LK", name: "سريلانكا", dialCode: "+94", maxLength: 9 },
  { code: "NP", name: "نيبال", dialCode: "+977", maxLength: 10 },
  { code: "AF", name: "أفغانستان", dialCode: "+93", maxLength: 9 },
  { code: "IR", name: "إيران", dialCode: "+98", maxLength: 10 },
];
